name: Web Scraper

on:
    schedule:
      # Schedule to run daily at 8 AM UTC
      - cron: '0 8 * * *'
    workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install
       
      - name: Install Playwright Dependencies
        run: npx playwright install-deps        

      - name: Build TypeScript
        run: npm run build

      - name: Install Playwright Browsers
        run: npm run install-browsers

      - name: Run Scraper
        run: npm start

      - name: Read State File Content
        id: read-file
        run: echo "file_content=$(cat state_file.txt)" >> $GITHUB_ENV

      - name: Send Email with Brevo
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp-relay.brevo.com
          server_port: 587
          username: ${{ secrets.BREVO_SMTP_USERNAME }}
          password: ${{ secrets.BREVO_SMTP_PASSWORD }}
          subject: "TABA - Scraper State File Content"
          body: |
            Hello,

            Here is the content of the state file:

            ${{ env.file_content }}

            Regards,
            Your Automation
          to: "orian.galk@gmail.com"
          from: "orian.galk@gmail.com"